# Generated by Django 5.0.6 on 2024-06-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='albumsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.TextField()),
                ('release_date', models.DateField()),
                ('ratings', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musicianmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='musicianModel',
        ),
    ]
