# Generated by Django 5.0.6 on 2024-06-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_albumsmodel_delete_musicianmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsmodel',
            name='ratings',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
