# Generated by Django 5.0.6 on 2024-06-09 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicianmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='musicianmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musicianmodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='musicianmodel',
            name='musician',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
