# Generated by Django 5.0.6 on 2024-06-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0007_musicianmodel_email_musicianmodel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicianmodel',
            name='email',
        ),
    ]
