# Generated by Django 5.0.6 on 2024-06-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
