# Generated by Django 5.0.6 on 2024-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_musicianmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
