# Generated by Django 5.0.6 on 2024-06-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0003_alter_musicianmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='instrument_type',
            field=models.CharField(choices=[('jazz', 'Jazz'), ('classic', 'Classic'), ('pop', 'Pop')], max_length=20),
        ),
    ]
